name: CI
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
      - run: cargo test --all-features
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
        with:
          components: rustfmt
      - name: rustfmt check
        uses: actions-rust-lang/rustfmt@4066006ec54a31931b9b1fddfd38f2fdf2d27143 # v1
  clippy_check:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: "Install/Update the Rust version"
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
        with:
          components: clippy
      - name: clippy "No Default Features"
        run: cargo clippy --workspace --no-default-features --all-targets
      - name: clippy "Default"
        run: cargo clippy --workspace --all-targets
      - name: clippy "All Features"
        run: cargo clippy --workspace --all-features --all-targets
  schema_check:
    name: config schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
      - name: regenerate schema
        run: cargo run --features schema-gen --bin gen-config-schema
      - name: check schema up to date
        run: git diff --exit-code -- config.schema.json
